version: '3.8'

services:
  web:
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      -  db-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
      - ./volumes/data/mariadb:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
volumes:
  db-data:
