# version: "3.9"

# services:
#   app:
#     image: php_mvc
#     build: ./docker
#     ports:
#       - "8888:80"
#     links:
#       - db
#     networks:
#       - mynetwork
#     environment:
#       DB_HOST: db
#       DB_PORT: ${DOCKER_MARIADB_PORT}
#       DB_NAME: ${DOCKER_MARIADB_DATABASE}
#       DB_USER: ${DOCKER_MARIADB_USER}
#       DB_PASSWORD: ${DOCKER_MARIADB_PASSWORD}
#     volumes:
#       - ./public/:/var/www/html
#       - ./vendor/:/var/www/vendor
#       - ./composer.json:/var/www/composer.json
#       - ./composer.lock:/var/www/composer.lock

#   db:
#     image: mariadb:latest
#     ports:
#       - "${DOCKER_MARIADB_PORT}:3307"
#     restart: unless-stopped
#     volumes:
#       - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
#       # - ./my.cnf:/etc/mysql/my.cnf  # Mount the custom my.cnf file
#     networks:
#       - mynetwork
    
#     environment:
#       DB_HOST: ${DB_HOST}
#       MARIADB_ROOT_PASSWORD: ${DOCKER_MARIADB_ROOT_PASSWORD}
#       MARIADB_USER: ${DOCKER_MARIADB_USER}
#       MARIADB_PASSWORD: ${DOCKER_MARIADB_PASSWORD}
#       MARIADB_DATABASE: ${DOCKER_MARIADB_DATABASE}
#     command: --innodb-use-native-aio=0

# networks:
#   mynetwork:
#     # driver: bridge
#     external: true

#------------------------------------------------------------------------
version: "3.9"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    links:
      - db
    networks:
      - mynetwork
    environment:
      DB_HOST: db
      DB_PORT: ${DOCKER_MARIADB_PORT}
      DB_NAME: ${DOCKER_MARIADB_DATABASE}
      DB_USER: ${DOCKER_MARIADB_USER}
      DB_PASSWORD: ${DOCKER_MARIADB_PASSWORD}
    volumes:
      - ./public/:/var/www/html
      - ./vendor/:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock

  db:
    image: mariadb:latest
    ports:
      - "${DOCKER_MARIADB_PORT}:3306"
    restart: unless-stopped
    volumes:
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
      - mynetwork
    
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${DOCKER_MARIADB_USER}
      MYSQL_PASSWORD: ${DOCKER_MARIADB_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MARIADB_DATABASE}
    command: --innodb-use-native-aio=0

networks:
  mynetwork:
